### PR TITLE
Leaderboard: hit the API PR

### PR DESCRIPTION
**Pull request by normainobary2021**
In this PR we added the following functionality:
- Implemented the "Refresh" button that will get all scores for a game created from Leaderboard API
- Implemented the form "Submit" button that will save a score for a game created
- Used arrow functions instead of the function keyword.
- Used async and await JavaScript features to consume the API.

### CODE REVIEW

**Review by elisha2kyakpo1 — APPROVED** [review]
Hi 👋 @normainobary2021, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The PR title and description looks professional✔️
- No linter errors✔️
- Descriptive commit messages✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by normainobary2021** [comment]
Thank you so much @elisha2kyakpo1 for that quick review. I am so happy

**Comment by normainobary2021** [comment]
Hello Elisha,
I have since submitted for my last review but it has been more than 40
minutes and no one has reviewed me yet.
I am worried about the time for the deadline, I emailed student success but
I am also kindly asking you, in such cases, what could I do?

Norman Ainobushoborozi

**Comment by normainobary2021** [comment]
Hello Elisha,
I was finally reviewed. No worries. Thank you very much

Norman

**Pull request merged**
